### ISSUE TITLE
can't export in mapbox gl  v.2.6.1 

### ISSUE THREAD

**Issue by mahmoudadel54** [watergis/mapbox-gl-export#30]
I use react to implement web map page to display mapbox map with export control:

`const map = new mapboxgl.Map({

      container: "map", // container ID

      style: "mapbox://styles/mapbox/streets-v11", // style URL

      center: [-74.5, 40], // starting position [lng, lat]

      zoom: 9, // starting zoom

      accessToken:"my token"});`
    //export control
    `map.addControl(new MapboxExportControl(), "top-right");`

when I clicked to export this error occurs to me:
![image](https://user-images.githubusercontent.com/58145645/143679094-11ca5d4c-6946-4516-8390-706580c5ae48.png)

Note: I initialize mapbox token at the beginning :
   mapboxgl.accessToken =
      "my token";

**Comment by JinIgarashi** [comment]
@mahmoudadel54 Sorry for inconvenience. I just found the instruction of README.md was wrong...I just have updated README.
This issue was fixed in https://github.com/watergis/mapbox-gl-export/pull/23.
For Mapbox v2, please use accessToken option in constructor of `MapboxExportControl`. Please see the below link's instruction.

https://github.com/watergis/mapbox-gl-export#if-you-want-to-use-a-basemap-from-mapbox

**Comment by JinIgarashi** [comment]
@mahmoudadel54 just let you know I have just released v2.0.0 with the latest mapbox-gl-js v2 now.

https://github.com/watergis/mapbox-gl-export/releases/tag/v2.0.0

**Comment by mahmoudadel54** [comment]
Hi Jin
Thanks for the update. I will check it ASAP.
